### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Fantu** [linuxmint/captain#1]
gdebi replacement seems interesting, I suggest avoiding mint specific deps for possible contributions from other interested developers out of mint, it could also be useful to include it in Debian to have it by default on Debian and all derivatives
for example gdebi despite development being abandoned for years has a huge user base: https://qa.debian.org/popcon.php?package=gdebi

it would be one of the projects I would like to contribute to, but unfortunately I don't have the time

**Comment by clefebvre** [comment]
Hi Fabio,

That's a good idea but I'll have to look into it first to see if and how we can do that.

Behind mint-common, the code uses aptdaemon, which is also semi-abandoned and which isn't in Debian.

We're also yet to rewrite the apturl portion, which also requires aptdaemon.

Captain is part of a bigger project for us to rationalize our APT UI interactions. We use a mixture of aptdaemon and packagekit, both have pros and cons.

We first need to decide if we want to rewrite aptdaemon or incorporate it into captain. And if we don't, then there's also the option to switch to packagekit.

**Comment by Fantu** [comment]
Thanks for reply, I think that can be useful write an email on debian-devel about this project and what you want to do to get any opinions, advice and if there is any Debian developer interested maybe join.
Maybe also cc'ing the gdebi maintainer (Michael Vogt <mvo@debian.org>), I thought he had completely abandoned Debian not seeing any contributions to gdebi for a long time but looking on [his Salsa profile](https://salsa.debian.org/mvo) there is some rare activity, the latest was about [python-apt](https://tracker.debian.org/pkg/python-apt)

**Comment by Fantu** [comment]
I found that @mvo5 have good activity on [github](https://github.com/mvo5), I try to mention it so maybe he finds out about this project, and maybe he can answer here what he thinks.

**Comment by mvo5** [comment]
Hey, thanks for reaching out. I sadly do not have much time these days for Debian but it's still near and dear to my heart. As for gdebi and friends - it's the same, I would love to see someone picking it up or (like it seems here) to rewrite it. The core principles should be sound and there is probably code to lift/reuse. Ideally python-apt would support the apt way of adding a single deb file to the cache which elimininates the manual resolver in gdebi but iirc that never got ported to python-apt :/

**Comment by clefebvre** [comment]
Hi @mvo5,

Thanks for all the contributions and the many other projects you brought us. They've been so useful and important to us.

**Comment by clefebvre** [comment]
Here are our current APT UI deps at a glance:

![image](https://github.com/user-attachments/assets/5b55776e-3ed7-4a97-b8a5-e98f50240324)

python-apt isn't shown here because we use it anywhere we don't need to show UI feedback. It's a rock.

We're trying to move away from synaptic because between aptdaemon and packagekit we've enough options, and not relying on synaptic allows us to not have it installed by default. The interaction between tools and synaptic relies on Gdk XID also, which is an issue long term for Wayland and an issue short-term because it leads to inter-process communication.

Packagekit is working well, especially when the tool needs tight UI integration with its own widgets. It's maintained upstream but it's not APT-centric. For instance we need to be able to purge packages.. and it doesn't support that. So we patch it a little bit.

Aptdaemon and apturl work great but they're not actively maintained and they only exist in Ubuntu. We patch them a little bit but we need to go further if we want good translations and design changes.

Same with gdebi. Debian patches it for important bug fixes. We brought in patches in Mint to revamp its UI, move it away from synaptic etc.. but we felt it was time to properly maintain translations and modify the scope and design.

The code brought into Captain is largely taken from the Mint version of gdebi. The .ui was copied over and elements which weren't used were removed. The project structure is new. The code was started from scratch but many little functions were imported from the Gdebi code, and the steps it follows were rewritten following those found in Gdebi.

Compared to Debian's GDebi, captain has the following main differences:

- Smaller score for the .deb installer: no Qt frontend, no CLI, no remote URL handling, no lintian integration.
- Added apturl functionality (not in master yet)
- Uses aptdaemon (via mint-common at the moment) instead of synaptic
- More modern UI
- Better translations

The portion of the code dedicated to using mintcommon-aptdaemon is tiny. It would be very easy to migrate it back to Synaptic and or to adapt it to packagekit. But it might be more interesting to consider forking aptdaemon and/or adding it to captain, because aptdaemon provides functionality we really enjoy and it really needs a few changes and active maintenance.

**Comment by Fantu** [comment]
I think is good to reach also aptdaemon maintainer, from d/control `XSBC-Original-Maintainer: Julian Andres Klode` seems was @julian-klode to see what he think and can suggest

**Comment by clefebvre** [comment]
From my notes I thought it was Sebastian Heinlein.

**Comment by Fantu** [comment]
Also from Debian result Julian: https://tracker.debian.org/pkg/aptdaemon
and the cause of remove from Debian is:
[Replaced by PackageKit](https://tracker.debian.org/news/771057/removed-111bzr982-1-from-unstable/)

**Comment by Fantu** [comment]
I started to improve packaging: https://github.com/linuxmint/captain/pull/3
In that I added also missed d/copyright, but I'm not sure is complete.
I suggest (not only for this project) adding in source files copyright and license information, including files taken from other project even if in original project was missed in the file (but present only on project information).
Should be fast adding at least SPDX-FileCopyrightText and SPDX-License-Identifier in the file headers

**Comment by clefebvre** [comment]
Thanks.

Please don't add legal/copyright/licensing info within the source files though. The only thing we should have in there, other than code are comments targeted at developers. The smaller these files are the better.

**Comment by Fantu** [comment]
I also think the too long copyright/license header in source file is not good, that method is minimal, with only 2 lines per file, or more if there are multiple copyrights and only some particular license require full text.
If you really don't want to have them in the files at least have them complete externally by updating d/copyright or even better something outside the packaging and more standard like maybe reuse, seems to have definition also with external file: https://reuse.software/spec-3.2/#reusetoml
I think the important thing is to not only define the license of your software but also to keep track of all the copyright and license information of parts taken externally.
Unfortunately, it has already happened in other mint software that the copyright and licenses of externally taken parts were not fully reported and it was difficult to find the information.
I was trying to give some suggestions to avoid it, for facilitate also the inclusion in distributions (like Debian but not only) where the license and copyright information must be complete and correct or such software cannot be included, and not risk discouraging any contributors who consider respect for copyright and licenses essential.

**Comment by clefebvre** [comment]
A ./reuse.toml should do the job nicely. Could the debian/copyright file be removed then or link/refer to it?

**Comment by MustafaKoca9** [comment]
> A ./reuse.toml should do the job nicely. Could the debian/copyright file be removed then or link/refer to it?

e-mail root@linuxmint.com check it out.

**Comment by Fantu** [comment]
> A ./reuse.toml should do the job nicely. Could the debian/copyright file be removed then or link/refer to it?

reuse is to use upstream (for the software), d/copyright is needed for the packaging and must remain but if the software provides a good system to manage licenses and copyright, such as reuse you can generate and update very easily and quickly, both reuse and DEP5 are machine-readable.
I haven't tried any automatic reuse tools yet, unfortunately up until now I've worked on software packages where in most cases the management of licenses and copyright is (or was) poor and in some cases I've wasted more time doing research and checks for d/copyright than all the rest of the packaging :(
Some are improved/improving recently, for example the latest I saw in these days is backintime is checking/fixing copyright/license things and switching to using spdx.

**Comment by Fantu** [comment]
I tested reuse convert from DEP5 and it considers not valid some deprecated license short name used by Debian.
In the weekend I did many tests of tool that help d/copyright management (https://wiki.debian.org/CopyrightReviewTools) relating to spdx short name, opened a discussion on debian-devel and other thing trying to help increase spdx name usage and I hope in future as default.
licensecheck (the most used) already have spdx name in DEP5 support, licenserecon (that help to find different for possible missed or wrong part in d/copyright) added spdx name support today, decopy (that I used mainly for generate starting d/copyright) have a work in progress.

-------------------

Returning to captain:
about [aptdaemon](https://tracker.debian.org/pkg/aptdaemon) fork I think is better to write before to debian-devel (especially since it was removed as not replaced by packagekit) to see if they recommend any better way to do what is needed and to ask if they would accept the inclusion of such a fork.

**Comment by clefebvre** [comment]
Although it's possible to use Packagekit instead of Aptdaemon, it's a lot more work for small tools and applications because it involves making your own widgets. Aptdaemon provides a set of dialogs which is really useful for scripts and small clients.

The main reason Debian removed aptdaemon afaik was because it wasn't actively maintained. It's worth noting that Aptdaemon was implemented in the first place because Packagekit didn't provide features that were specific enough to APT.

We're using both technologies ourselves, they're both great but they both have pros and cons for different use cases.
